export type item = {
  name: string;
  quantity: number;
};

export const data: item[] = [
  { name: 'Item 1', quantity: 25 },
  { name: 'Item 2', quantity: 49 },
  { name: 'Item 3', quantity: 19 },
  { name: 'Item 4', quantity: 9 },
  { name: 'Item 5', quantity: 6 },
  { name: 'Item 6', quantity: 3 },
  { name: 'Item 7', quantity: 36 },
  { name: 'Item 8', quantity: 13 },
  { name: 'Item 9', quantity: 12 },
  { name: 'Item 10', quantity: 28 },
  { name: 'Item 11', quantity: 19 },
  { name: 'Item 12', quantity: 34 },
  { name: 'Item 13', quantity: 17 },
  { name: 'Item 14', quantity: 42 },
  { name: 'Item 15', quantity: 32 },
  { name: 'Item 16', quantity: 30 },
  { name: 'Item 17', quantity: 5 },
  { name: 'Item 18', quantity: 38 },
  { name: 'Item 19', quantity: 1 },
  { name: 'Item 20', quantity: 10 },
  { name: 'Item 21', quantity: 37 },
  { name: 'Item 22', quantity: 42 },
  { name: 'Item 23', quantity: 23 },
  { name: 'Item 24', quantity: 44 },
  { name: 'Item 25', quantity: 43 },
  { name: 'Item 26', quantity: 4 },
  { name: 'Item 27', quantity: 7 },
  { name: 'Item 28', quantity: 16 },
  { name: 'Item 29', quantity: 27 },
  { name: 'Item 30', quantity: 20 },
  { name: 'Item 31', quantity: 8 },
  { name: 'Item 32', quantity: 39 },
  { name: 'Item 33', quantity: 43 },
  { name: 'Item 34', quantity: 21 },
  { name: 'Item 35', quantity: 39 },
  { name: 'Item 36', quantity: 26 },
  { name: 'Item 37', quantity: 39 },
  { name: 'Item 38', quantity: 32 },
  { name: 'Item 39', quantity: 34 },
  { name: 'Item 40', quantity: 1 },
  { name: 'Item 41', quantity: 34 },
  { name: 'Item 42', quantity: 4 },
  { name: 'Item 43', quantity: 19 },
  { name: 'Item 44', quantity: 12 },
  { name: 'Item 45', quantity: 1 },
  { name: 'Item 46', quantity: 37 },
  { name: 'Item 47', quantity: 2 },
  { name: 'Item 48', quantity: 28 },
  { name: 'Item 49', quantity: 22 },
  { name: 'Item 50', quantity: 2 },
];
